- snapshots/README.md
- "screenshotting" -> "snapshotting" for consistency
- mostly some nits, looks good overall!
> Update README copy

- snapshots/sample/app/build.gradle.kts
- snapshots/sample/ui-module/build.gradle.kts
- snapshots/snapshots/build.gradle.kts
I can't recall why I originally had set 24, but lowering to 23 seems to work just fine!
Resolves ET-2199
> Support minSdk 23

- README.md
- snapshots/README.md
- Remove beta labels
- Highlights main source set Compose snapshot generation
- Adds details about variants
- Adds clarification on keys for diffing
Resolves ET-2211, ET-2317
> Doc updates

- .github/workflows/performance-release.yml
- gradle-plugin/plugin/performance-project-template/build.gradle.kts
- gradle/libs.versions.toml
- performance/CHANGELOG.md
- performance/README.md
Nothing holding us back any longer! Also adds the publish action.
Resolves ET-2380
> Prepare for Performance 2.0.0

- .github/workflows/performance-release.yml
> Add env variables for perf deploy

- build.gradle.kts
- gradle-plugin/plugin/build.gradle.kts
- gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePlugin.kt
- gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePluginExtension.kt
- snapshots/sample/app/build.gradle.kts
Remove KSP and make experimentalTransformEnabled default
Remove additional unuseds
> Remove KSP and make experimentalTransformEnabled default

- snapshots/snapshots-shared/src/main/kotlin/com/emergetools/snapshots/shared/ComposePreviewSnapshotConfig.kt
Pending https://github.com/EmergeTools/emerge-android/pull/148
> Remove deprecated fields

- gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePlugin.kt
- gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePluginExtension.kt
Allows for escape hatches for each specific product to be enabled/disable if needed by clients.
> Add enabled field to all product options in gradle plugin for ability to opt-out

- gradle-plugin/plugin/build.gradle.kts
- gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePlugin.kt
- gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePluginExtension.kt
- gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/upload/ArtifactMetadata.kt
- gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/upload/BaseUploadTask.kt
- gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/util/MapUtils.kt
- gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/util/dependencies/Dependencies.kt
- gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/util/dependencies/DependencyUtils.kt
- snapshots/sample/app/build.gradle.kts
Adds a dependency/module report to uploads. This includes each file (or class) from that module/library and the path to that file.
> Add dependency and module data

- .github/workflows/gradle-plugin-checks.yml
- gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePluginExtension.kt
- gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/upload/ArtifactMetadata.kt
- gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/upload/BaseUploadTask.kt
Package as the raw json file in our upload for potential later debugging.
> Include GitHub event data in upload for debugging

- gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/reaper/ReaperPreflight.kt
- gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/reaper/Register.kt
- gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/Register.kt
- gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/SnapshotsPreflight.kt
- gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/util/preflight/Preflight.kt
> [Gradle plugin][Snapshots] Add Snapshots preflight check task

- gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/size/Register.kt
- gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/size/SizePreflight.kt
- gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/Register.kt
Add preflight task for size analysis
> Size analysis preflight task

- reaper/reaper/src/main/kotlin/com/emergetools/reaper/Reaper.kt
- reaper/reaper/src/main/kotlin/com/emergetools/reaper/ReaperInternal.kt
Also use this opportunity to introduce an 'options' object which can be used to support future Reaper options (OkHttp customization etc)
> Add ability to disable logcat to Reaper

- distribution/sample/app/build.gradle.kts
- gradle/libs.versions.toml
- performance/sample/app/build.gradle.kts
- reaper/sample/app/build.gradle.kts
- reaper/sample/manuallyInitializedApp/build.gradle.kts
- reaper/sample/stress/build.gradle.kts
- snapshots/sample/app/build.gradle.kts
- snapshots/sample/ui-module/build.gradle.kts
- snapshots/snapshots/build.gradle.kts
Brings us up to best practices per https://developer.android.com/develop/ui/compose/compiler
> Update to use compose compiler gradle plugin

- gradle-plugin/plugin/build.gradle.kts
Previously the supported version classpath files would resolve the
dependencies and write them to a file at configuration time which is bad
for performance. This moves it to task execution time.
Before:
https://scans.gradle.com/s/2xtnax5u2cpa6/performance/dependency-resolution?toggled=dependency-resolution-configuration-user-initiated#dependency-resolution-configuration-user-initiated
After:
https://scans.gradle.com/s/h56uktu6oeguw/performance/dependency-resolution#dependency-resolution-configuration-user-initiated
Note the durations above seem insignificant but if they require
downloading dependencies that aren't yet available, it means they must
be done at configuration time in serial (instead of in parallel at
execution time).
> Move supported version classpath files to execution time.

- gradle-plugin/plugin/build.gradle.kts
- gradle/libs.versions.toml
Reverts EmergeTools/emerge-android#406
> Revert "Update Gradle Plugin Publish Plugin"

- distribution/distribution/build.gradle.kts
- gradle-plugin/plugin/build.gradle.kts
- gradle/libs.versions.toml
- reaper/reaper/build.gradle.kts
Also fix missing junit platform launcher
> Update to Junit 5.12

- gradle-plugin/CHANGELOG.md
I had to double check myself, lol.
> What year is it?

- .github/workflows/snapshots-sample-app.yml
- gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/Register.kt
- gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/transform/MergeClasses.kt
- gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/transform/PreviewFiles.kt
- gradle.properties
This drove me nuts since it was working fine on my machine but apparently CI was processing the files in a different order.
> Do a second pass to fix file ordering problems

- snapshots/snapshots-annotations/build.gradle.kts
- snapshots/snapshots-shared/build.gradle.kts
Note: this also removes the git from the meta-inf. Let me know if we actually use it.
> Use Gradle's built-in meta-inf functionality.

- .github/workflows/snapshots-release.yml
- .github/workflows/snapshots-snapshot-deploy.yml
Realized we don't have a snapshots snapshot release workflow, so this adds it!
> Add snapshots snapshot publish workflow

- gradle/libs.versions.toml
> Stable gradle plugin version
