.github/workflows/snapshots-checks.yml
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/SnapshotSaver.kt

By generating the key as a combo of the fqn and the user-specified name, we exposed ourselves to key-clash issues across builds if the test simply moved.
Therefore, for generating our compare keys (and filenames), we'll essentially "revert" here to the existing solution of normalizing the user-defined name.

Update key name to be reliant only on user defined name to avoid failed diffs

---

gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/perf/LocalPerfTest.kt
gradle/libs.versions.toml
snapshots/sample/app/build.gradle.kts
snapshots/sample/build.gradle.kts
snapshots/sample/ui-module/build.gradle.kts
snapshots/snapshots-processor/src/main/kotlin/com/emergetools/snapshots/processor/PreviewProcessor.kt

- Add support for multi-module snapshot testing to the `:snapshots:sample` project.
- Adds explicit import for composable function to generated snapshot tests.
- Fixes a bug in the gradle plugin where output of local perf test wasn't logged to user.
- Minor cleanups, increase KSP version to get rid of warning logs.

Add multi-module snapshotting to sample, fix local perf test task output

---

gradle-plugin/README.md
gradle-plugin/plugin/performance-project-template/build.gradle.kts
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePlugin.kt
performance/sample/performance/build.gradle.kts
performance/sample/performance/src/main/AndroidManifest.xml
performance/sample/performance/src/main/java/com/emergetools/performance/sample/test/ExamplePerformanceTest.kt

Rather than implicitly including perf testing SDK on behalf of users, locking us into a version, we'll now make it an explicit import and add it as a dependency in the performance project template.
Noted the breaking changes in the migration section of the plugin readme.

Emerge test SDK as an explicit import now

---

gradle-plugin/README.md
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePlugin.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePluginExtension.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/upload/BaseUploadTask.kt
performance/sample/app/build.gradle.kts
performance/sample/app/src/main/res/values/strings.xml

Just a nice-to-have, by default sets the `apiToken` property to be the `EMERGE_API_TOKEN` environment variable.

Set default API token value to be environment variable

---

.github/workflows/gradle-plugin-release.yml
gradle-plugin/README.md

Standardize our publishing so we no longer have to run from local environments. Will add similar deploy workflows for the perf/snapshots SDKs in the near future.
Necessary secrets have been added.

Add GH workflow for publishing gradle plugin

---

build.gradle.kts
gradle-plugin/README.md
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePlugin.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePluginExtension.kt
gradle/libs.versions.toml
snapshots/README.md
snapshots/sample/app/build.gradle.kts
snapshots/sample/ui-module/build.gradle.kts

Supports/fixes submodule Composable snapshot generation. Kotlin compilation was failing for submodules as we didn't apply our workaround from #20 to generate snapshot tests from the main source set for modules other than the main app module.
This PR fixes that, as well as makes our workaround to move generated KSP tests to our own custom source location the default behavior as it actually works quite well. 
Since we're making this the default, I also removed `includeFromMainSourceSet` as it's no longer relevant.
Test cases:

Support dependent module snapshot generation

---

gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePlugin.kt

Used for communication from our perf test orchestrator to the test runner. This will automatically apply for the perf module so clients don't have to.

Add Ktor as dependency for perf test projects

---

snapshots/snapshots-processor/src/main/kotlin/com/emergetools/snapshots/processor/preview/ComposablePreviewSnapshotBuilder.kt
snapshots/snapshots-processor/src/main/kotlin/com/emergetools/snapshots/processor/preview/ComposePreviewUtils.kt
snapshots/snapshots-processor/src/main/kotlin/com/emergetools/snapshots/processor/shared/ComposePreviewSnapshotConfig.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/SnapshotImageMetadata.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/shared/ComposePreviewSnapshotConfig.kt

The fqn is respective of the test, not the composable. So to show the proper fqn of the composable in our UI, we'll need to add it to metadata.
This sets that and updates the processor to fill it in based on the `@Preview` annotate function's fqn, or packageName + simpleName

Add original composable name to compose configuration for showing in UI

---

snapshots/snapshots-processor/src/main/kotlin/com/emergetools/snapshots/processor/PreviewProcessor.kt
snapshots/snapshots-processor/src/main/kotlin/com/emergetools/snapshots/processor/preview/ComposablePreviewSnapshotBuilder.kt
snapshots/snapshots-processor/src/main/kotlin/com/emergetools/snapshots/processor/shared/ComposePreviewSnapshotConfig.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/EmergeSnapshots.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/SnapshotImageMetadata.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/SnapshotSaver.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/shared/ComposePreviewSnapshotConfig.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/shared/Utils.kt
snapshots/snapshots/src/test/kotlin/com/emergetools/snapshots/KeyNameTest.kt
snapshots/snapshots/src/test/kotlin/com/emergetools/snapshots/SnapshotSaverTests.kt

We want our backend to be responsible for determining what information to show in our UI, so this PR will change up both our keys and how displayName is handled. KeyName is intended to be opaque to the user and stable across test runs.
- KeyName is a combination of fqn of the composable, along with a concatenated variant postfix.
- This could potentially break when new variants are added in the future, but that's intentional/ok since those would technically be different snapshots which could cause a flaky diff.
- `functionName`, taken from the `originalFqn` will be used as the title in our UI
- User defined name from the `@Preview` annotation, set as `name` in `ComposePreviewSnapshotConfig` will be used as subtitle if present. This matches iOS behavior.
- Additional variant information …

Update keys and displayName for better Compose support

---

.github/workflows/gradle-plugin-checks.yml
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePluginExtension.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/upload/BaseUploadTask.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/util/GitHub.kt

Adds support for automatic handling of GitHub event data. From internal testing and client experience, GitHub values for sha/baseSha are related to the merge commit/reliant on the checkout action to properly set respectively. This leads to issues calling the GitHub API and finding the proper build to compare against.
Rather than rely on users to set this, we can make some safe assumptions ourselves and go ahead and set the data if it's present. This should make GitHub CI integreations far easier.
Resolves ET-2264

Automatically set sha/baseSha from GitHub event info if relevant

---

gradle-plugin/plugin/build.gradle.kts
gradle-plugin/plugin/src/functionalTest/kotlin/com/emergetools/android/gradle/NoVcsEmergePluginTest.kt
gradle-plugin/plugin/src/functionalTest/kotlin/com/emergetools/android/gradle/SimpleEmergePluginTest.kt
gradle-plugin/plugin/src/functionalTest/kotlin/com/emergetools/android/gradle/base/EmergeGradleRunner.kt
gradle-plugin/plugin/src/functionalTest/kotlin/com/emergetools/android/gradle/utils/EnvUtils.kt
gradle-plugin/plugin/src/functionalTest/resources/github-event-mocks/mock_pr_event.json
gradle-plugin/plugin/src/functionalTest/resources/github-event-mocks/mock_push_event.json
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePlugin.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePluginExtension.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/internal/SaveExtensionConfigTask.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/upload/BaseUploadTask.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/util/Git.kt

Adds tests for recent addition of automatic GitHub PR info setting #42.
This approaches the test in a bit of a clever manner. In our functional Gradle tests, we have no way to “inspect” the emerge extension config as part of the test, as the gradle runner doesn’t expose it.
To get around this, I creataed a custom debug task (only created when a special debug flag is added) that would output the config as JSON to a location of our choosing passed through an arg. For testing, we’ll just enable the debug flag, write the file, then perform normal assertions on the contents.

Add tests for GitHub event sha/baseSha setting and respective infra for testing config

---

gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/UploadSnapshotBundle.kt

A client hit a configuration cache violation with the `artifactMetadata` field, as it wasn't marked as `Internal` (or input/output) for Gradle to ignore the value of for considering tasks up to date.
This marks it internal so Gradle should ignore. Will integration test with HN.
Resolves ET-2223

Fix config cache violation

---

detekt/detekt.yml
settings.gradle.kts
snapshots/sample/app/build.gradle.kts
snapshots/sample/app/src/main/kotlin/com/emergetools/snapshots/sample/ui/TextRowWithIcon.kt
snapshots/snapshots-annotations/build.gradle.kts
snapshots/snapshots-annotations/src/main/kotlin/com/emergetools/snapshots/annotations/IgnoreEmergeSnapshot.kt
snapshots/snapshots-processor/src/main/kotlin/com/emergetools/snapshots/processor/PreviewProcessor.kt

- Adds `snapshots-annotations` module/dependency which will contain any annotations to be used from any source set.
- Adds `@IgnoreEmergeSnapshot` annotation which will tell our `snapshots-processor` to ignore the Preview when generating snapshots
- Adds handling for the new annotation to `snapshots-processor`
Deploy/version bump will be in follow up.
Resolves ET-2331

Add snapshots-annotations and a new IgnoreEmergeSnapshot annotation which will ignore generating a snapshot test for a given preview

---

gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePlugin.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/upload/BaseUploadTask.kt

Outputs the response json from the `/upload` endpoint to a file, `upload_response.json` that will be saved into the `build/emergetools` folder. This handles a client request to programmatically handle the URL/uploadId so they can ingest into their internal dashboards without tailing/parsing logs.
Resolves ET-2280

Output upload response data to file for users to ingest JSON

---

snapshots/snapshots-processor/src/main/kotlin/com/emergetools/snapshots/processor/PreviewProcessor.kt

Seems compilation will fail for some setups if internals are referenced from generated snapshots. This temporarily skips them, with plans for supporting private and internal functions in the future.
Resolves ET-2408

Skip internal functions for time being

---

snapshots/sample/app/src/main/kotlin/com/emergetools/snapshots/sample/ui/FontScalePreviews.kt
snapshots/sample/app/src/main/kotlin/com/emergetools/snapshots/sample/ui/TextRowWithIcon.kt
snapshots/snapshots-processor-test/src/test/kotlin/com/emergetools/snapshots/processor/PreviewProcessorTest.kt
snapshots/snapshots-processor-test/src/test/resources/PreviewProcessorTest/multipreview_function_with_two_previews_and_additional_preview_produces_three_snapshots/input/FontScalePreviews.kt
snapshots/snapshots-processor-test/src/test/resources/PreviewProcessorTest/multipreview_function_with_two_previews_and_additional_preview_produces_three_snapshots/input/MultiPreviewComposable.kt
snapshots/snapshots-processor-test/src/test/resources/PreviewProcessorTest/multipreview_function_with_two_previews_and_additional_preview_produces_three_snapshots/output/MultiPreviewComposable_-1121164302_GenSnapshot.kt
snapshots/snapshots-processor-test/src/test/resources/PreviewProcessorTest/multipreview_function_with_two_previews_and_additional_preview_produces_three_snapshots/output/MultiPreviewComposable_1326053438_GenSnapshot.kt
snapshots/snapshots-processor-test/src/test/resources/PreviewProcessorTest/multipreview_function_with_two_previews_and_additional_preview_produces_three_snapshots/output/MultiPreviewComposable_GenSnapshot.kt
snapshots/snapshots-processor-test/src/test/resources/PreviewProcessorTest/multipreview_function_with_two_previews_produces_two_snapshots/input/FontScalePreviews.kt
snapshots/snapshots-processor-test/src/test/resources/PreviewProcessorTest/multipreview_function_with_two_previews_produces_two_snapshots/input/MultiPreviewComposable.kt
snapshots/snapshots-processor-test/src/test/resources/PreviewProcessorTest/multipreview_function_with_two_previews_produces_two_snapshots/output/MultiPreviewComposable_-849881519_GenSnapshot.kt
snapshots/snapshots-processor-test/src/test/resources/PreviewProcessorTest/multipreview_function_with_two_previews_produces_two_snapshots/output/MultiPreviewComposable_1597336221_GenSnapshot.kt
snapshots/snapshots-processor/src/main/kotlin/com/emergetools/snapshots/processor/PreviewProcessor.kt
snapshots/snapshots-processor/src/main/kotlin/com/emergetools/snapshots/processor/preview/ComposePreviewUtils.kt
snapshots/snapshots-processor/src/main/kotlin/com/emergetools/snapshots/processor/utils/MapUtils.kt
snapshots/snapshots-processor/src/main/kotlin/com/emergetools/snapshots/processor/utils/PreviewFinderUtils.kt
snapshots/snapshots-shared/src/main/kotlin/com/emergetools/snapshots/shared/ComposePreviewSnapshotConfig.kt

Adds MultiPreview annotation support ([Android docs](https://developer.android.com/jetpack/compose/tooling/previews#preview-multipreview)). This currently only supports one-level of multipreview support, i.e. currently you can't "chain" multipreviews together. This acceptable for the time being per client requests.
Resolves ET-2318

Multipreview support

---

performance/performance/src/main/java/com/emergetools/test/utils/perfetto/PerfettoUtils.kt
performance/sample/app/src/main/kotlin/com/emergetools/performance/sample/MainActivity.kt
performance/sample/perfTesting/src/main/java/com/emergetools/performance/sample/test/ExamplePerformanceTest.kt

Adds support for async spans (`Trace.beginAsyncSection`/`Trace.endAsyncSection`) in local runner for debugging.

Support async spans in local runner

---

snapshots/sample/app/src/main/kotlin/com/emergetools/snapshots/sample/ui/TextRowWithIcon.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/compose/SnapshotVariantProvider.kt

Our compositionLocal we use for snapshots didn't update the context used within it, meaning other locales wouldn't get picked up properly though resources. This sets the local context using the configuration which results in proper locale setting:

Fix locale not working

---

snapshots/sample/app/src/main/kotlin/com/emergetools/snapshots/sample/ui/SnapshotTestingPreview.kt
snapshots/sample/app/src/main/kotlin/com/emergetools/snapshots/sample/ui/TextRowWithIcon.kt
snapshots/snapshots-processor/src/main/kotlin/com/emergetools/snapshots/processor/PreviewProcessor.kt
snapshots/snapshots-processor/src/main/kotlin/com/emergetools/snapshots/processor/utils/PreviewFinderUtils.kt

Second part of correctly resolving multi-previews, now we can resolve arbitrary levels of multi-preview annotations.
1. Finds all symbols that have a direct or transitive `@Preview` annotation by recursively checking annotation classes. Transitive `@Preview` annotations would be those from a multi-preview.
2. Once we know the symbols annotated with a preview annotation, a second step filters that down to only functions.
3. After we have the functions, we have to then fetch all direct or transitive preview annotations on the function and build up a list of unique snapshot configs. This bit was tricky and does repeat some of the step 1 work from earlier, but not too concerned about the perf impact here.
4. Snapshot generation then proceeds like normal.
**Testing:**
I created a new …

Add recursive lookup for transitive preview annotations

---

gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePlugin.kt

Moves the `emergeLocal<variant>Test` task onto the app module. Also adds some debug logging to help debug situations where we can't find the perf module.
Resolves ET-2482

Move local performance task to be registered on app module, add some debug logging

---

gradle-plugin/plugin/performance-project-template/build.gradle.kts
gradle-plugin/plugin/src/functionalTest/kotlin/com/emergetools/android/gradle/MultiProjectFlavorsBuildTypesEmergePluginTest.kt
gradle-plugin/plugin/src/functionalTest/resources/gradle-project-dirs/multi-project-with-flavors-buildtypes/app/build.gradle
gradle-plugin/plugin/src/functionalTest/resources/gradle-project-dirs/multi-project-with-flavors-buildtypes/app/src/main/AndroidManifest.xml
gradle-plugin/plugin/src/functionalTest/resources/gradle-project-dirs/multi-project-with-flavors-buildtypes/build.gradle
gradle-plugin/plugin/src/functionalTest/resources/gradle-project-dirs/multi-project-with-flavors-buildtypes/performance/build.gradle
gradle-plugin/plugin/src/functionalTest/resources/gradle-project-dirs/multi-project-with-flavors-buildtypes/performance/src/main/AndroidManifest.xml
gradle-plugin/plugin/src/functionalTest/resources/gradle-project-dirs/multi-project-with-flavors-buildtypes/settings.gradle
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePlugin.kt
performance/sample/app/build.gradle.kts
performance/sample/perfTesting/build.gradle.kts

I realized we were generating a performance testing variant that was intended to match every app variant, and then we'd check to ensure that variant matched, which lead to some strange cases. This was unnecessary anyway, as the variant of the test app isn't important for our perf testing.
Therefore, we'll now just generate a single debug variant for the perf testing project. We'll also generate a perf test upload/local test task for all appVariants that leverages the single debug perf testing variant, which was the intention from the beginning. Added a test to verify this works as expected for multiple flavors and build types.
This will break existing tasks, so will require a 2.2 version bump in the near future. I might try to package a few more changes in before that release, but we'll …

Adjust perf testing variants to only have a single debug variant, and properly generate tasks for app variants

---

gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePlugin.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePluginExtension.kt
snapshots/snapshots-processor-test/src/test/kotlin/com/emergetools/snapshots/processor/PreviewProcessorTest.kt
snapshots/snapshots-processor-test/src/test/resources/PreviewProcessorTest/multipreview_internal_function_with_two_previews_produces_no_snapshots_without_arg/input/FontScalePreviews.kt
snapshots/snapshots-processor-test/src/test/resources/PreviewProcessorTest/multipreview_internal_function_with_two_previews_produces_no_snapshots_without_arg/input/MultiPreviewComposable.kt
snapshots/snapshots-processor-test/src/test/resources/PreviewProcessorTest/multipreview_internal_function_with_two_previews_produces_two_snapshots/input/MultiPreviewComposable.kt
snapshots/snapshots-processor-test/src/test/resources/PreviewProcessorTest/multipreview_internal_function_with_two_previews_produces_two_snapshots_with_arg/input/FontScalePreviews.kt
snapshots/snapshots-processor-test/src/test/resources/PreviewProcessorTest/multipreview_internal_function_with_two_previews_produces_two_snapshots_with_arg/input/MultiPreviewComposable.kt
snapshots/snapshots-processor-test/src/test/resources/PreviewProcessorTest/multipreview_internal_function_with_two_previews_produces_two_snapshots_with_arg/output/MultiPreviewComposable_-1707151673_GenSnapshot.kt
snapshots/snapshots-processor-test/src/test/resources/PreviewProcessorTest/multipreview_internal_function_with_two_previews_produces_two_snapshots_with_arg/output/MultiPreviewComposable_140597883_GenSnapshot.kt
snapshots/snapshots-processor-test/src/test/resources/PreviewProcessorTest/standalone_preview_function_with_internal_preview_produces_no_snapshot_test_without_arg/input/TestComposable.kt
snapshots/snapshots-processor-test/src/test/resources/PreviewProcessorTest/standalone_preview_function_with_internal_preview_produces_one_snapshot_test_with_arg/input/TestComposable.kt
snapshots/snapshots-processor-test/src/test/resources/PreviewProcessorTest/standalone_preview_function_with_internal_preview_produces_one_snapshot_test_with_arg/output/TestComposable_GenSnapshot.kt
snapshots/snapshots-processor/src/main/kotlin/com/emergetools/snapshots/processor/PreviewProcessor.kt

Adds a new property on the `snapshots` block to enable internal previews as an experimental feature. For the most part, internal preview usage has been stable, but we've seen cases where it fails, so we want to make sure there's a failsafe mechanism in place so it won't unexpectedly break builds.

Make internal snapshots generation based on experimental snapshot property

---

gradle/libs.versions.toml
performance/sample/app/build.gradle.kts
snapshots/sample/app/build.gradle.kts
snapshots/snapshots/build.gradle.kts

Was working to integrate with a potential customer today and we had to explicitly add these. Changing them to API dependencies to ensure consumers no longer need to explicitly add them themselves since we're reliant.

Add necessary dependencies as api dependencies

---

.github/workflows/snapshots-sample-app.yml
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePluginExtension.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/perf/LocalPerfTest.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/LocalSnapshots.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/util/Git.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/util/GitHub.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/util/Process.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/util/adb/AdbHelper.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/util/providers/GitBaseShaValueSource.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/util/providers/GitCurrentBranchValueSource.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/util/providers/GitHubPrNumberValueSource.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/util/providers/GitHubRepoNameValueSource.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/util/providers/GitHubRepoOwnerValueSource.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/util/providers/GitShaValueSource.kt

Fixes remaining configuration cache violations from the gradle plugin. All stemmed from running external processes from the inputs: https://docs.gradle.org/8.2/userguide/configuration_cache.html#config_cache:requirements:external_processes
Followed best practice using `ValueSource` implementations to provide the proper git info for each.

Fix configuration cache violations

---

snapshots/snapshots-annotations/build.gradle.kts
snapshots/snapshots-shared/build.gradle.kts
snapshots/snapshots/build.gradle.kts

Some clients have hit issues when using Kotlin 1.7 as we compile with Kotlin 1.9. This adds language support for 1.7+, which upon testing in a repro project, fixes issues running on apps with 1.7.
From the `languageVersion` docs:
```
/**
* Provide source compatibility with the specified version of Kotlin
* Possible values: "1.4 (deprecated)", "1.5 (deprecated)", "1.6", "1.7", "1.8", "1.9", "2.0 (experimental)", "2.1 (experimental)"
* Default value: null
*/
```

Add Kotlin language support for 1.7+

---

gradle-plugin/README.md
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePluginExtension.kt

A client pointed out that `gitLabOptions` is the only available gitLab configuration in vcs options, which our docs incorrectly use `gitLab`. To match longer term conventions, this introduces the expected `gitLab` configuration block and keeps `gitLabOptions` around to prevent breaking existing integrations. I'll remove `gitLabOptions` in a future major release as it'll be a breaking change.

Add gitLab vcs config block to match docs

---

gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePlugin.kt

Noticed a few places were using differing build directory entries, so we'll standardize with this!

Consistent build directory

---

gradle/libs.versions.toml
performance/CHANGELOG.md
performance/performance/src/main/java/com/emergetools/test/EmergeLocalJUnit4ClassRunner.kt

After this change errors looks like this:

Show stack trace for errors in performance tests

---

gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePlugin.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePluginExtension.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/instrumentation/snapshots/SnapshotsPreviewRuntimeRetentionTransform.kt

Creates an instrumentation/transform that finds all `Preview`/`Preview.Container` (repeatable) annotations and forces them to be runtime visible. This is a workaround to https://issuetracker.google.com/issues/168524920, as D8 will unexpectedly strip Binary/Class annotations.
Also:
- adds `debugOptions` and the ability to force invalidate a transform using a system time to make sure transforms aren't cached (taken from [here](https://arc.net/l/quote/xcfypmfs)).
- Adds `snapshots.experimentalTransformEnabled` which can act as an opt-in to this behavior until we've fully tested and are ready for 1.0

Create SnapshotsPreviewRuntimeRetentionTransform to change Previews to runtime retention

---

gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePlugin.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/perf/GeneratePerfProject.kt
gradle/libs.versions.toml

Running https://github.com/autonomousapps/gradle-best-practices-plugin to identify issues raised this as a potential config cache violation. Moves all invokes of `getProject` to be done at configuration time instead of task invocation time. 
Confirmation run of the best practices after this change confirms we addressed the violation.

Fix configuration cache violation where we reference project from GeneratePerformanceProjectTask's TaskAction

---

.gitignore
gradle-plugin/plugin/build.gradle.kts
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePlugin.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/LocalSnapshots.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/utils/ComposeSnapshots.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/utils/PreviewUtils.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/util/adb/AdbHelper.kt
gradle/libs.versions.toml

Adds support for our new KSP-less snapshot invoking to the LocalSnapshots task, allowing us (and users) to remove KSP entirely!
Runs by finding all previews/multipreviews directly from the instrumented dex, then passing JSON to reflective invoker test.

Support localSnapshots task for new reflective invoking

---

snapshots/sample/app/src/main/kotlin/com/emergetools/snapshots/sample/ui/TextRowWithIcon.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/compose/EmergeComposeSnapshotReflectiveParameterizedInvoker.kt

Fixes private Preview method invocations, using `Class.getDeclaredMethod` as a fallback to find methods that are hidden in `class.methods`. We then mark the methods as accessible for invoking with reflection. Confirmed working locally on https://github.com/EmergeTools/nowinandroid/pull/1
Also implements a bit nicer naming for our reflective parameterized tests. It used to just show the index of the test, but now will show something like:
```
reflectiveComposableInvoker[66 com.google.samples.apps.nowinandroid.feature.settings.PreviewSettingsDialog]
```
with the unique keyName for the composable snapshot directly in the name, making debug/attribution easier.

Handle snapshoting private preview methods and improve parameterized test naming

---

gradle-plugin/README.md
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePlugin.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePluginExtension.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/LocalSnapshots.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/UploadSnapshotBundle.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/utils/PreviewUtils.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/util/network/EmergeUploadRequest.kt

From a bit of user feedback, some users wanted the ability to hide all previews that were private rather than adding `@IgnoreEmergeSnapshot`. This adds that functionality with a Gradle plugin property - `includePrivatePreviews`, which will default to `true`, but optionally users can set to false to exclude `@Preview` annotated functions that are `private`.
Backend component implemented separately.

Add includePrivatePreviews option to allow disabling private previews from being snapshotted

---

snapshots/sample/app/src/main/kotlin/com/emergetools/snapshots/sample/ui/TextRowWithIcon.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/compose/ComposeSnapshotter.kt

A 0x0 bitmap could crash the entire test run if not properly caught. It seems this is due to the exception being thrown from the body of the `post` runnable, which is uncaught on a separate thread.
To better handle, we can just return a null bitmap and save an error. In a future PR I'll add more robust error handling.
Resolves ET-3433

Handle issue where empty bitmap could crash entire test run

---

gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/utils/ComposeSnapshots.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/utils/PreviewUtils.kt
snapshots/sample/app/src/main/kotlin/com/emergetools/snapshots/sample/ui/TextRowWithIcon.kt
snapshots/snapshots-shared/src/main/kotlin/com/emergetools/snapshots/shared/ComposePreviewSnapshotConfig.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/compose/DeviceUtils.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/compose/SnapshotVariantProvider.kt
snapshots/snapshots/src/test/kotlin/com/emergetools/snapshots/compose/DeviceUtilsTest.kt

Adds support for the `device` Preview annotation parameter.
Leverages a regex to parse custom values, or cross-references a known ID->device spec map that uses https://m3.material.io/blog/device-metrics to calculate the proper width/height dp and scaling factor.

Support device Preview annotation parameter

---

snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/compose/ComposeSnapshotter.kt

Now that devices are up to spec, our implementation of showSystemUI no longer works when used in tandem with `device`. 
Until we can come along with a full solution, we'll temporarily disable our custom handling. This should result in the snapshots still succeeding, albeit without the surrounding system UI. We'll plan a full fix for `showSystemUI` in a later release of snapshots.

Temporarily remove showSystemUi

---

reaper/reaper/src/main/kotlin/com/emergetools/reaper/ReaperReportUploadWorker.kt

Reaper reports contain an additional newline at present:
```
"aujsMBJlOyY=\n"
```

[reaper] Remove extra newline in reports

---

.github/workflows/snapshots-sample-app.yml

Noticed in #216 we're missing a base snapshots build, as the commit it's based off of didn't touch snapshots code and therefore didn't run snapshots. 
This fixes the sample snapshots workflow to always run on main pushes to ensure we always have a valid build.

Fix snapshot workflow to always run on main pushes

---

gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePlugin.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/reaper/InitializeReaper.kt

Rather than having an explicit initialize task, I figured we could have the initialize (upload) task "hook" the default `bundle` AGP task. That way users can build their AAB as-is but we'll handle the uploading side of things.

[Gradle plugin][Reaper] Hook default bundle task rather than having explicit initialize task

---

gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePlugin.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/perf/Register.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/reaper/Register.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/size/Register.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/Register.kt

`EmergePlugin` was getting a bit large/hard to navigate, so I figured moving the task registration logic to the respective packages seems to make sense to me.
Additionally, this groups the tasks by their respective product when running the `:project:tasks` task to make it easier to find the relevant task a user needs to invoke.

[Gradle plugin] Cleanup and move task registration logic into separate files in relevant packages

---

gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/perf/UploadPerfBundle.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/reaper/InitializeReaper.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/size/UploadAAB.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/size/UploadAPK.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/UploadSnapshotBundle.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/upload/BaseUploadTask.kt

When running any task with the `dryRun` property set to true, there would be a pretty aggressive crash, despite this being expected:
This better handles a successful dryRun.

Better handle dryRun

---

reaper/reaper/src/main/kotlin/com/emergetools/reaper/ReaperInternal.kt

I found in https://github.com/EmergeTools/hackernews/pull/107 that when adding reaper as an `implementation` dependency, it would also be added to non-intended variants (debug in that case). Upon the manifest placeholder for publishableApiKey being empty, we'd hit a `Manifest com.emergetools.PUBLISHABLE_API_KEY must be set and non-empty.` error.
The thing is, this is intentional, as we don't want to init reaper for non-intended variants. 
So rather than fatally erroring here, we're exit the init early and log a warning to make it clear this is an intended situation. I use the `INSTRUMENTED` placeholder to indicate this.

[Reaper] Use instrumented manifest placeholder as indication reaper is enabled and end early if not rather than fatal erroring

---

gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/reaper/PreflightReaper.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/reaper/Register.kt

The reaper preflight task currently hooks the `minify<variant>WithR8` task. This results in failures if reaper isn't properly set up, and since it hooks the minify task, this could throw for cases where we don't want to throw.
This moves the verify task behind the enabled check, so while it won't register for all variants outright, it will at least prevent breaking cases where it shouldn't

Put reaper preflight behind enabled check as well to ensure we don't hook tasks we shouldn't be

---

snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/SnapshotSaver.kt

We've historically hard crashed from this logic to ensure we don't overwrite a file with the same key. This hard crash seems to cause the underlying instrumentation to crash in some rare occasions.
Working to see if we can better run tests in-silo to prevent this, but in the meantime we should try to avoid taking the entire instrumentation down.

Don't hard error on file already existing

---

snapshots/snapshots-shared/src/main/kotlin/com/emergetools/snapshots/shared/ComposePreviewSnapshotConfig.kt

Currently, if apiLevel or wallpaper are set, we won't properly respect that in the unique key for the preview. This results in two different previews writing to the same file, which can cause a clobber/error.
While we still don't support these params first-class, this will prevent a clobber and will render the snapshot without the apiLevel/wallpaper params respected, but without an error.

Add additional compose preview params to ensure unsupported preview params don't clobber other valid previews

---

snapshots/sample/app/src/androidTest/kotlin/com/emergetools/snapshots/sample/ExampleSkippedTest.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/runner/SnapshotsRunner.kt

When we mark a test as ignored/skipped, this takes a non-negligible amount of time and can still result in shards being assigned to the skipped tests, despite not actually executing anything.
By removing any acknowledgement of the test, this should allow us to truly "skip" the test, saving resources and preventing edge cases where shards/emulators are assigned to skipped tests.

Remove skipping logic and ignore a test entirely if not a snapshot  test

---

reaper/reaper/src/main/kotlin/com/emergetools/reaper/Manifest.kt
reaper/reaper/src/main/kotlin/com/emergetools/reaper/OnStopLifecycleObserver.kt
reaper/reaper/src/main/kotlin/com/emergetools/reaper/Reaper.kt
reaper/reaper/src/main/kotlin/com/emergetools/reaper/ReaperInternal.kt
reaper/reaper/src/main/kotlin/com/emergetools/reaper/ReaperReportErrorWorker.kt
reaper/reaper/src/main/kotlin/com/emergetools/reaper/ReaperReportUploadWorker.kt
reaper/reaper/src/main/kotlin/com/emergetools/reaper/Tracing.kt
reaper/sample/app/build.gradle.kts
reaper/sample/app/src/main/kotlin/com/emergetools/reaper/sample/screen/StoryDetailScreen.kt

Rework how Reaper is initialized to avoid main thread work where possible.
The new startup flow is as follows:
There are two methods for initializing Reaper:
1. Manually via `Reaper.init`
2. Automatically via `ReaperInitializer`
Either way `ReaperInternal.init` is invoked.
- `ReaperInternal.init` method creates `ReaperImpl`
- then schedules the remaining startup to happen in `DEFERRED_START_MS` via `Handler.postDelayed`.
- The deferred startup (`mainThreadStart`) runs on the main thread and:
- Creates a thread with a `Looper` named `ReaperWorker`
- Sets up an `OnStopLifecycleObserver` to call `ReaperImpl.finalizeReport`
- And finally posts a message to `ReaperWorker` (`workerThreadStart`)
- `workerThreadStart` calls
- `ReaperImpl.sweepReports` to action reports left from previous sessions …

Move almost all work off the main thread

---

gradle-plugin/plugin/src/test/kotlin/com/emergetools/android/gradle/instrumentation/reaper/ReaperClassLoadTest.kt
reaper/reaper/src/main/kotlin/com/emergetools/reaper/Paths.kt
reaper/reaper/src/main/kotlin/com/emergetools/reaper/ReaperImpl.kt
reaper/reaper/src/main/kotlin/com/emergetools/reaper/ReaperInternal.kt
reaper/reaper/src/main/kotlin/com/emergetools/reaper/Tracing.kt
reaper/reaper/src/test/kotlin/com/emergetools/reaper/ReaperImplTest.kt

Split the logic for Reaper into two parts:
1. ReaperImpl which handles all the logic 
2. ReaperImpl.Delegate which handles all the IO and anything Android specific
This allows for:
- easy unit testing of the business logic (a few examples added in this PR)
- auditing all the IO for correct handling of errors e.g. `ENOSPC (No space left on device)` (in a follow up)

Reaper split business logic from IO

---

snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/compose/EmergeComposeSnapshotReflectiveParameterizedInvoker.kt

Test orchestrator doesn't allow whitespace in test names 🤔

Remove whitespace from Parameterized invoker to allow for test orchestrator

---

snapshots/snapshots-shared/build.gradle.kts
snapshots/snapshots-shared/src/main/kotlin/com/emergetools/snapshots/shared/ComposePreviewSnapshotConfig.kt
snapshots/snapshots-shared/src/test/kotlin/com/emergetools/snapshots/shared/ComposePreviewSnapshotConfigTest.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/compose/EmergeComposeSnapshotReflectiveParameterizedInvoker.kt

Fixes bugs that were blocking us from leveraging Android test orchestrator. Particularly there is a bug in older versions where the length of the test name would cause orchestrator to fail. This is not well documented but is present in a few ASG discussions and this issue https://github.com/android/android-test/issues/1935

Fix bugs that are blocking use of Android test orchestrator

---

snapshots/sample/app/src/main/kotlin/com/emergetools/snapshots/sample/ui/PortraitLandscapeView.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/compose/ComposeSnapshotter.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/compose/DeviceUtils.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/compose/SnapshotVariantProvider.kt
snapshots/snapshots/src/test/kotlin/com/emergetools/snapshots/compose/DeviceUtilsTest.kt

Fixes device specs to be true-to-size to reference devices. Also adjusts to properly scale custom specs. Added a repro case of a troublesome client snapshot that wasn't rendering in landscaped.
Verified with a sxs run against Google's compose preview snapshotting library, Emerge matches 1:1 on all device specs now. Android Studio images (copied directly from the previews) appear smaller, and dimensions do not match the reference device specs, so I believe matching the expected device dimensions like we do now is preferred over 1:1 matching of AS.
Also checked all reference devices against the outputted dimensions from Emerge snapshots after this change and all match 1:1.

[Snapshots] Fix device specs

---

snapshots/sample/app/src/main/kotlin/com/emergetools/snapshots/sample/ui/IconGroup.kt
snapshots/sample/app/src/main/kotlin/com/emergetools/snapshots/sample/ui/MultiUserRow.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/compose/ComposableInvoker.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/compose/ComposeSnapshotter.kt

A client tested out our latest 1.3.0 rc01 today and caught two edge cases in our PreviewParameter handling:
1. If the previewParameter provided a primitive, we weren't properly coercing it to the non-Kotlin wrapper type. We need to coerce it to the java primitive/java wrapper type for proper unboxing.
2. if the previewParameter was a nested generic, like `List<User>`, we weren't properly getting the providerType, which led to an error being thrown. We'll now handle nested parameterized types.
Also realized `ComposeSnapshotter` was getting a bit unwieldy, so abstracted it out to `ComposeInvoker`, inspiration taken from [here](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui-tooling/src/jvmMain/kotlin/androidx/compose/ui/tooling/ComposableInvoker.jvm. …

Fix issue with nested typed/primitive preview params

---

snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/compose/ComposableInvoker.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/compose/ComposeSnapshotter.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/compose/previewparams/PreviewParamUtils.kt

Our custom implementation of reflective invoking was hitting some snags around typing/param resolution. After looking into how stock Android compose tooling does it, I figured it would be best for us to replicate their's as close as possible:
- [ComposableInvoker.kt](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui-tooling/src/jvmMain/kotlin/androidx/compose/ui/tooling/ComposableInvoker.jvm.kt)
- [PreviewActivity.kt](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui-tooling/src/androidMain/kotlin/androidx/compose/ui/tooling/PreviewActivity.android.kt)
This brings us up to almost a 1:1 invoking pattern as them, while taking into account some of our first-class compose args/helpers. This has resulted in a …

Update compose invoker to better replicate PreviewActivity behavior

---

gradle/libs.versions.toml

1.7.0 of `compose-runtime` (any compose-bom after `2024.08.00`) has a breaking change in our snapshots SDK when targeting an app with 1.6.8 or lower (bom `2024.08.00`). 
When building our SDK with a 1.7.0+, a `rememberComposableLambda` function is called that was [added in 1.7.0](https://android-review.googlesource.com/c/platform/frameworks/support/+/2692852/37/compose/runtime/runtime/src/commonMain/kotlin/androidx/compose/runtime/internal/ComposableLambda.kt#625). When our snapshots SDK is used as an `androidTestImplementation` dependency against an app with a lower compose version, this function is not present, which leads to a `NoSuchMethodError` upon trying to invoke the snapshot.
For now, this should be able to be fixed with a simple version drop, and longer term we can work through …

Lower compose version to avoid breaking change added in 1.7.0

---

gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePlugin.kt

Internal version of https://github.com/EmergeTools/emerge-android/pull/306 for secrets with tests

Use providers.gradleProperty for project isolation compatibility

---

gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePlugin.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePluginExtension.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/LocalSnapshots.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/Register.kt
snapshots/sample/app/build.gradle.kts
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/SnapshotSaver.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/compose/ComposableInvoker.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/compose/ComposeSnapshotter.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/compose/DeviceUtils.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/compose/EmergeComposeSnapshotReflectiveParameterizedInvoker.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/compose/previewparams/PreviewParamUtils.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/util/Profiler.kt

Generates a .folded profile file for each test when the `snapshotOptions.profile` property is set.

Snapshots performance profiling

---

snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/compose/ComposeSnapshotter.kt

In an effort to improve performance, I went back to question if we could remove test orchestrator again. Test orchestrator was added to get around pesky uncaught exceptions which would result in the overall instrumentation process being taken down.
This adds a default uncaught exception handler that will save error metadata and ensure we finish the preview activity. Testing against some repro cases (with orchestrator off), this seems to catch crashes that previously would take down the instrumentation process.

Add setDefaultUncaughtExceptionHandler to catch exceptions that would previously take down process

---

.gitignore
benchmark/build.gradle.kts
gradle-plugin/plugin/src/functionalTest/kotlin/com/emergetools/android/gradle/EmergePluginTest.kt
gradle-plugin/plugin/src/functionalTest/kotlin/com/emergetools/android/gradle/LoggingEmergePluginTest.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/EmergePlugin.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/internal/LogExtensionTask.kt
gradle.properties

Added a new `logExtension` Gradle task to debug Emerge plugin configuration instead of printing using `-i` flag in Gradle.
Previously this would cause git operations during the configuration phase when running a gradle build with the `-i` flag or info level logging enabled. This resolves #322 
- Created a new `LogExtensionTask` to display Emerge plugin configuration
- Moved configuration logging logic from `EmergePlugin` to dedicated task
- Added `.tool-versions` to `.gitignore`
- Removed `targetSdk` from benchmark module
- Enhanced test assertions with output verification
- Added Gradle performance optimization properties
Run `./gradlew logExtension` to view the current Emerge configuration

Introduce separate logExtension task to log VCS options

---

gradle-plugin/plugin/build.gradle.kts

Remove mustrunafter test task configuration.
This should improve performance when configuration cache is enabled, allowing tasks within the same project to run in parallel.

Remove mustrunafter test task configuration

---

.github/workflows/gradle-plugin-checks.yml
gradle-plugin/detekt/baseline.xml
gradle-plugin/plugin/build.gradle.kts
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/base/BasePreflightTask.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/base/BaseUploadTask.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/internal/LogExtensionTask.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/internal/SaveExtensionConfigTask.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/perf/GeneratePerfProject.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/perf/LocalPerfTest.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/perf/UploadPerfBundle.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/reaper/InitializeReaper.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/reaper/ReaperPreflight.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/size/SizePreflight.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/size/UploadAAB.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/size/UploadAPK.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/LocalSnapshots.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/PackageSnapshotArtifacts.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/SnapshotsPreflight.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/UploadSnapshotBundle.kt

This PR:
* Enables stricter plugin validation to ensure all future added tasks are marked correctly.
* Adds DisableCachingByDefault for all tasks which should not be cached.
* Adds CacheableTask to all Gradle tasks with well defined inputs and outputs
* Removes some code to create output directories since Gradle does this for you
* Removes some lines of code that might delete task outputs (causing the task to rerun)

Add cacheable task annotations and proper inputs

---

benchmark/build.gradle.kts
distribution/distribution/build.gradle.kts
distribution/sample/app/build.gradle.kts
gradle/libs.versions.toml
performance/performance/build.gradle.kts
performance/sample/app/build.gradle.kts
reaper/reaper/build.gradle.kts
reaper/sample/app/build.gradle.kts
reaper/sample/manuallyInitializedApp/build.gradle.kts
reaper/sample/stress/build.gradle.kts
settings.gradle.kts
snapshots/sample/app/build.gradle.kts
snapshots/sample/ui-module/build.gradle.kts
snapshots/snapshots/build.gradle.kts

This avoids repeatings the compileSdk version across the repo.
This settings plugin pattern might be a good pattern for our own plugin to be able to share configuration across projects.

Centralize android gradle plugin configuration with settings plugin

---

gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/reaper/Register.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/Register.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/util/VariantUtils.kt

This code would previously resolve dependencies at configuration time in order to check for our dependencies.
This moves that code to instead return a provider which is only evaluated when the value is obtained.
In this build scan before this change you can see the line is printed before the task executes:
https://scans.gradle.com/s/lfejlsyx2hyqk/console-log?page=1#L12
In this build scan after this change you can see the line is printed during the task execution:
https://scans.gradle.com/s/6zvdxhqjhnedk/console-log?page=1#L13
This fixes an issue reported by a customer where these lines would be printed and therefore the configurations would be resolved even though they did not use reaper.

Fix resolving dependencies at configuration time

---

gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/base/BaseUploadTask.kt

Hackernews builds are missing dependency info. After a deeper dive, I noticed the `metadata.dependencyMetadataZipPath` was missing. This is due to us clobbering the value after setting when we set the metadata with the Github event data. This ensures we re-write the metadata preserving data set on it.

Fix bug where artifactMetadata was missing some fields due to being overwritten with original copy

---

gradle/libs.versions.toml

Saw some issues in prod with 1.8.0, so for the time being we'll fallback to the latest working version (confirmed locally) then try to bump at a future time.

Downgrade Kotlinx serialization json to 1.7.3

---

gradle-plugin/plugin/build.gradle.kts
gradle/libs.versions.toml

Add back Gradle Plugin Publish Plugin update
This fixes the task dependencies.
Here’s a semi-successful build scan that failed due to lack of credentials and not task dependency issues https://scans.gradle.com/s/7xif3z63ahgyu

Bump publish plugin to 1.3.0 (again)

---

gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/util/GitHub.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/util/Repositories.kt
gradle-plugin/plugin/src/test/kotlin/com/emergetools/android/gradle/util/RepositoriesTest.kt

This fixes bugs where the reponame would not be set on CI because the git url was not being parsed correctly

Correctly parse git/github/gitlab urls in all environments

---

gradle-plugin/plugin/build.gradle.kts

This wires the task up to the sourcesets which automatically wires up
the task dependencies saving a lot of boilerplate

Wire up task to sourcesets.

---

distribution/sample/app/build.gradle.kts
reaper/sample/app/build.gradle.kts
reaper/sample/manuallyInitializedApp/build.gradle.kts
reaper/sample/stress/build.gradle.kts
snapshots/sample/app/build.gradle.kts

This is unecessary since we automatically gather these via the Gradle plugin.

Remove unecessary configuration

---

gradle/libs.versions.toml
snapshots/sample/app/src/main/kotlin/com/emergetools/snapshots/sample/ui/MediaPickerDemo.kt

The MediaPickerDemo screen seems unused so I'm not sure how to test it
but this fixes the compiler error.

Update AndroidXActivity and MediaPickerDemo

---

.github/workflows/integration-hackernews.yml
gradle-plugin/plugin/build.gradle.kts
settings.gradle.kts

This adds this repo as a composite build to the hacker news app and builds it.
You can see in this build scan that the composite build is being applied to the `:app` module.
https://scans.gradle.com/s/fq5pdezizjitk/build-dependencies?toggled=W1sxXSxbMSwwXSxbMSwwLFs0ODVdXV0

Add hackernews functional integration test

---

gradle/libs.versions.toml
snapshots/sample/app/build.gradle.kts
snapshots/sample/app/src/main/kotlin/com/emergetools/snapshots/sample/ui/DevicePreviews.kt
snapshots/sample/app/src/main/kotlin/com/emergetools/snapshots/sample/ui/PortraitLandscapeView.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/compose/ComposeSnapshotter.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/compose/DeviceUtils.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/compose/SnapshotVariantProvider.kt

A client requested support for Wear devices. This adds support for the two primary wear devices (`wearos_large_round`, `wearos_small_round`), I intentionally skipped support for rect & square as the [comment suggests not using](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:wear/wear-tooling-preview/src/main/java/androidx/wear/tooling/preview/devices/WearDevice.kt;l=33?q=WearDevice.kt&ss=androidx/platform/frameworks/support).

Add support for Wear devices

---

.github/workflows/distribution-release.yml
.github/workflows/performance-release.yml
.github/workflows/reaper-release.yml
.github/workflows/snapshots-release.yml

When trying to publish snapshots, there were multiple staging repos being opened in sonatype. This was resulting in errors actually publishing.
After a bit of googling, I found https://stackoverflow.com/questions/72664149/gradle-maven-publish-sonatype-creates-multiple-repositories-that-cant-be-clos. Nelson recent added the gradle.properties file with parallel=true in https://github.com/EmergeTools/emerge-android/pull/327/files#diff-3d103fc7c312a3e136f88e81cef592424b8af2464c468116545c4d22d6edcf19, so this just disables for the release workflows.

Disable parallel for release workflows

---

gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/util/Repositories.kt
gradle-plugin/plugin/src/test/kotlin/com/emergetools/android/gradle/util/RepositoriesTest.kt
settings.gradle.kts

Here you can see the repoOwner and repoName properly set on bitbucket.
[link](https://bitbucket.org/emerge_test/emerge-android/pipelines/results/15/steps/%7Bf5ba90b9-21cd-46f7-bc93-ea6ff0b35f23%7D#line=13-108)

Add bitbucket to the regex as well and test using bitbucket urls

---

gradle-plugin/plugin/build.gradle.kts
gradle-plugin/plugin/src/functionalTest/kotlin/com/emergetools/android/gradle/base/EmergeGradleRunner.kt
gradle/libs.versions.toml

This uses some of the convenience provided by using [Tony's Gradle TestKit Support Plugin.](https://github.com/autonomousapps/dependency-analysis-gradle-plugin/tree/main/testkit)
The goal of this change is to allow us to rewrite some of the tests to
stop using `GradleRunner.withPluginClasspath()`. See point #1 in the
above readme or for more information on issues with `withPluginClasspath` see these issues: https://github.com/gradle/gradle/issues/28285
https://github.com/gradle/gradle/issues/22466
I believe that the mixing of the classpath is causing some tests to succeed even though they should fail. We shall see. [Either way this PR](https://github.com/EmergeTools/emerge-android/pull/453) has revealed that this is a problem.

Use Gradle TestKit Support Plugin for testing

---

.github/workflows/gradle-plugin-snapshot-release.yml
.github/workflows/snapshots-release.yml
gradle-plugin/plugin/build.gradle.kts
gradle/libs.versions.toml

This adds the configuration to publish to maven central and the maven central snapshot repository for testing.
What this does:
* This will publish a snapshot on every main branch build when the version ends in `-SNAPSHOT`.
* The release workflow will also publish to maven central.
Note this hasn’t been tested.

Add maven central and snapshot publishing configuration

---

build.gradle.kts

This puts all our plugins in the root project in order to ensure that
the buildscript classpath is the same for all subprojects. This improves
performance by avoiding loading a new buildscript classpath for each
subproject.
Before: https://scans.gradle.com/s/aups343hmsby4/build-dependencies?toggled=W1s2XSxbNV0sWzYsMF0sWzUsMF0sWzNdLFszLDBdLFsyXSxbMiwwXSxbMF0sWzAsMF0sWzRdLFs0LDBdLFs3XSxbNywwXV0
After: https://scans.gradle.com/s/cxfqmjpcpuouk/build-dependencies?toggled=W1swXSxbMV1d

Cleanup buildscript classpath

---

snapshots/sample/app/src/main/kotlin/com/emergetools/snapshots/sample/ui/LocalePreviews.kt
snapshots/sample/app/src/main/kotlin/com/emergetools/snapshots/sample/ui/PortraitLandscapeView.kt
snapshots/sample/app/src/main/kotlin/com/emergetools/snapshots/sample/ui/TextRowWithIcon.kt
snapshots/sample/app/src/main/res/values-ar/strings.xml
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/compose/SnapshotVariantProvider.kt
snapshots/snapshots/src/test/kotlin/com/emergetools/snapshots/UtilsTest.kt

A client raised an issue mentioning RTL language variants were not properly updating the layout direction of the composable. Upon further inspection, we were not overriding the layout direction as well as setting the Configuration's layout direction.
This now properly snapshots RTL languages (just AR/HE for now) and adds a sample arabic snapshot to confirm/act as an integration test moving forward.

Properly support RTL languages

---

benchmark/build.gradle.kts
distribution/distribution/build.gradle.kts
distribution/integration/build.gradle.kts
distribution/sample/app/build.gradle.kts
gradle-plugin/plugin/build.gradle.kts
gradle.properties
gradle/libs.versions.toml
performance/performance/build.gradle.kts
reaper/reaper/build.gradle.kts
reaper/sample/app/build.gradle.kts
reaper/sample/stress/build.gradle.kts
snapshots/sample/app/build.gradle.kts
snapshots/sample/ui-module/build.gradle.kts
snapshots/snapshots-shared/build.gradle.kts
snapshots/snapshots/build.gradle.kts

We had some places in the code that were using both. This can lead to unpredictable results if using the wrong class. I noticed this since I was trying to refactor our tests and picked the wrong junit version and something wasn’t working.
This also simplifies the dependency setup.
I also had to bump up the Gradle heap size since I was facing OOMs when trying to run all the tests locally.

Separate Junit4 and Junit5.

---

.github/workflows/gradle-plugin-checks.yml
.github/workflows/gradle-plugin-release.yml
.github/workflows/gradle-plugin-snapshot-deploy.yml
gradle-plugin/README.md

Note: this slightly changes our regular release publication steps since
we need to make sure to bump the version and add `-SNAPSHOT` after
publishing.
This also renames the snapshot deployment workflow from
`gradle-plugin-snapshot-release.yml` to `gradle-plugin-snapshot-deloy.yml` for clarity.

Add instructions on publishing snapshots.

---

gradle-plugin/plugin/src/functionalTest/kotlin/com/emergetools/android/gradle/NoVcsEmergePluginTest.kt
gradle-plugin/plugin/src/functionalTest/kotlin/com/emergetools/android/gradle/SimpleEmergePluginTest.kt
gradle-plugin/plugin/src/functionalTest/kotlin/com/emergetools/android/gradle/base/EmergeGradleRunner.kt
gradle-plugin/plugin/src/functionalTest/kotlin/com/emergetools/android/gradle/base/EmergeGradleRunner2.kt

We don't need the java 11/17 codepaths since we are already copying in
all the environment variables from the parent build.

Remove unneeded code related to java version.

---

gradle-plugin/plugin/src/functionalTest/kotlin/com/emergetools/android/gradle/ConfigurationCacheTest.kt
gradle-plugin/plugin/src/functionalTest/kotlin/com/emergetools/android/gradle/base/EmergeGradleRunner.kt
gradle-plugin/plugin/src/functionalTest/kotlin/com/emergetools/android/gradle/projects/AbstractAndroidProject.kt
gradle-plugin/plugin/src/functionalTest/kotlin/com/emergetools/android/gradle/projects/MultiProjectProject.kt
gradle-plugin/plugin/src/functionalTest/kotlin/com/emergetools/android/gradle/projects/SimpleGradleProject.kt

This will unblock the PR to use GR8 to relocate dependencies.
This also restructures the `SimpleGradleProject` to inherit from `AbstractAndroidProject` so we can also use common functions in `MultiProjectProject`

Use new test runner for ConfigurationCacheTest

---

reaper/CHANGELOG.md
reaper/reaper/src/main/kotlin/com/emergetools/reaper/NullHashTracker.kt
reaper/reaper/src/main/kotlin/com/emergetools/reaper/Reaper.kt
reaper/reaper/src/main/kotlin/com/emergetools/reaper/ReaperInternal.kt

Add `Reaper.fuseOff` an API to permanently disable Reaper from collecting hashes for the lifetime of the
process and discard any hashes collected so far.
The expected use case is to reduce the cost the Reaper when it is never going to be enabled
(for example in the control arm of an experiment where the treatment arm is enabling Reaper).
Reaper has some cost even when not initialized, this is due to the requirement of detecting
code used very early during startup. 'Early startup' hashes are accumulated then flushed once
Reaper is initialized. If Reaper is never initialized this flush never happens and a limited
(but potentiality significant) amount of memory can be 'leaked'.
This provides an API to 'free' that memory and prevent future collection.

[reaper] Add Reaper.fuseOff

---

gradle/libs.versions.toml

The current release is `0.0.4`, the planned next release is `0.0.5` which means that we should have the version set to `0.0.5-SNAPSHOT`.

Fix distribution version

---

distribution/distribution/build.gradle.kts
performance/performance/build.gradle.kts
reaper/reaper/build.gradle.kts
snapshots/snapshots-annotations/build.gradle.kts
snapshots/snapshots-shared/build.gradle.kts
snapshots/snapshots/build.gradle.kts

This causes artifacts to need to be rebuilt as this is constantly
changing.

Remove build timestamp.

---

gradle.properties

This should prevent the daemon from shutting down since it is often
running out of metaspace.

Increase metaspace heap size.

---

distribution/distribution/build.gradle.kts
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/LocalSnapshots.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/util/Git.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/util/Process.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/util/adb/AdbHelper.kt
performance/performance/build.gradle.kts
reaper/reaper/build.gradle.kts
settings.gradle.kts
snapshots/snapshots-annotations/build.gradle.kts
snapshots/snapshots-shared/build.gradle.kts
snapshots/snapshots/build.gradle.kts
tools/build.gradle.kts

Since we ignore adb errors this task could fail but then be cached never
alowing you to execute it again.
This also renames our exec function so that the intention is clear.

Disable caching for LocalSnapshots task.

---

gradle/libs.versions.toml

We test against AGP 8.0 so we can be sure we are compatible there.

Synchronize AGP versions between plugin and the rest of the build

---

gradle/libs.versions.toml
tools/build.gradle.kts

This wasn't working since we are unbundling the kotlin stdlib dependency
from all our libraries. It is a good practice to unbundle the kotlin
stdlib for library authors to not cause conflicts.

Fix tools/gen

---

.github/workflows/snapshots-sample-app.yml
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/Register.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/transform/MergeClasses.kt
gradle.properties

This uses the AGP api to get the compiled classes from our project directory.

Enable First Party Snapshots by default

---

gradle-plugin/plugin/build.gradle.kts
gradle-plugin/plugin/rules.pro
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/dv/DvHelpers.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/base/BaseUploadTask.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/perf/Register.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/perf/UploadPerfBundle.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/reaper/InitializeReaper.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/reaper/Register.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/size/Register.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/size/UploadAAB.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/size/UploadAPK.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/Register.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/UploadSnapshotBundle.kt
gradle/libs.versions.toml

This adds a Build Scan Link for easy navigation whenever we log a URL to the console
Example: https://scans.gradle.com/s/wykjydx5yfybo

Add Develocity Build Scan links when logging urls

---

gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/Register.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/transform/FindPreviewsAcrossProjects.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/transform/PreviewFiles.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/transform/SnapshotAggregatorClassVisitor.kt

Wires up the existing `includePrivatePreview` extension configuration property with the new first-party/gradle-based Compose preview JSON generation. 
Tested with #533 and worked as-expected!

Add support for ignoring private previews to new plugin preview transform

---

distribution/distribution/build.gradle.kts
gradle-plugin/plugin/build.gradle.kts
reaper/reaper/build.gradle.kts
snapshots/snapshots/build.gradle.kts

This removes guava and configures our libraries for single variant publication since there is no difference between debug and release.

Remove Guava and use single variant publication

---

README.md
distribution/README.md
distribution/distribution/build.gradle.kts
distribution/integration/build.gradle.kts
distribution/sample/app/build.gradle.kts
gradle-plugin/CHANGELOG.md
gradle-plugin/plugin/performance-project-template/build.gradle.kts
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/reaper/ReaperPreflight.kt
gradle-plugin/plugin/src/main/kotlin/com/emergetools/android/gradle/tasks/snapshots/SnapshotsPreflight.kt
performance/README.md
performance/performance/build.gradle.kts
performance/sample/perfTesting/build.gradle.kts
reaper/README.md
reaper/reaper/build.gradle.kts
reaper/reaper/src/main/kotlin/com/emergetools/reaper/Reaper.kt
reaper/sample/app/build.gradle.kts
reaper/sample/manuallyInitializedApp/build.gradle.kts
reaper/sample/stress/build.gradle.kts
snapshots/README.md
snapshots/snapshots/build.gradle.kts

SDK implies something that is built against but our libraries do not
require developers to build anything against these. Using the word
library should clarify this.

Use library instead of SDK

---

distribution/distribution/build.gradle.kts
reaper/reaper/build.gradle.kts
snapshots/snapshots/build.gradle.kts

This will fix our snapshot deploy failure: https://github.com/EmergeTools/emerge-android/actions/runs/13987525374/job/39163974567
For more details on the bug see this: https://github.com/gmazzo/gradle-buildconfig-plugin/issues/226
IMO, we should get rid of BuildConfig in the future.

Workaround for bug in BuildConfig lib not allowing us to publish.

---

gradle/libs.versions.toml
snapshots/snapshots/build.gradle.kts
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/SnapshotImageMetadata.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/SnapshotSaver.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/compose/EmergeComposeSnapshotReflectiveParameterizedInvoker.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/models/ComposePreviewSnapshotConfig.kt
snapshots/snapshots/src/main/kotlin/com/emergetools/snapshots/models/ComposeSnapshots.kt

The tricky replacement was the sealed class which was handled by the `JsonClassDiscriminatorin` KotlinX Serialization. I used moshi's `PolymorphicJsonAdapterFactory` to replace that. The produced JSON should be the same.

Use Moshi instead of KotlinX Serialization

---

.github/workflows/reaper-checks.yml

See failing test here: https://github.com/EmergeTools/emerge-android/actions/runs/14834970401/job/41645969870?pr=595
As well as the list of deprecated devices here: https://firebase.google.com/docs/test-lab/android/available-testing-devices#deprecated

Remove deprecated devices.

---

settings.gradle.kts
snapshots/snapshots-universal-invoker/build.gradle.kts
snapshots/snapshots-universal-invoker/src/main/AndroidManifest.xml

Adds a universal invoker app that we can use to target any arbitrary client app for testing. Build with:
```
./gradlew :snapshots:snapshots-universal-invoker:assembleDebug -PtargetPackage=com.test.app
```
Install then run the snapshots instrumentation with ADB. Docs to come

Add universal snapshot APK

---

.github/workflows/distribution-release.yml
.github/workflows/gradle-plugin-release.yml
.github/workflows/performance-release.yml
.github/workflows/reaper-release.yml
.github/workflows/snapshots-release.yml

Seems like snapshots should work with configuration cache but releases
will not. https://vanniktech.github.io/gradle-maven-publish-plugin/central/#uploading-with-manual-publishing
This should hopefully fix this error: https://github.com/EmergeTools/emerge-android/actions/runs/16035916230/job/45247535472

Disable configuration cache to enable publishing to maven central.
